package com.app.weatherhaven.retrofit.coldshelter

data class ColdRow(
    val CHK1_YN: String,
    val CHK2_YN: String,
    val CHK3_YN: String,
    val CHK4_YN: String,
    val CHK5_YN: String,
    val CHK6_YN: String,
    val CHK7_YN: String,
    val CHK8_YN: String,
    val CHK9_YN: String,
    val C_DT_END: String,
    val C_DT_STRT: String,
    val C_END: String,
    val C_END_WD: String,
    val C_STRT: String,
    val C_STRT_WD: String,
    val EQUP_TYPE: String,
    val G2_ID: Double,
    val G2_XMAX: String,
    val G2_XMIN: Double,
    val G2_YMAX: String,
    val G2_YMIN: String,
    val HEAT1_CNT: Double,
    val HEAT2_CNT: Double,
    val HEAT3_CNT: Double,
    val HEAT4_CNT: Double,
    val R_AREA_NM: String,
    val R_AREA_SQR: Double,
    val R_DETL_ADD: String,
    val R_SEQ_NO: String,
    val USE_PRNB: Double,
    val USE_YN: String,
    val YEAR: String
)